<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>附录 G — 加州禁烟：SCM/RCM/SDID – 因果推断：政策评估中的识别思维与实证设计</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../notebooks/ch06_did/A06_did_method_selection.html" rel="next">
<link href="../../notebooks/ch04_fixed_effects/fixed_effects_practical_notes.html" rel="prev">
<link href="../../images/book-logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e8fb9d25728d58bfeac61b497e4a6629.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-57a92833092fd6dc0d7710b6bdfff9c5.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7ef202e96c563d31d9e5226e4d6cabf9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-490ba4e843cb1303a232ed0c676384f2.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../lectures/appendix/A01_hci_policy_background.html">附录</a></li><li class="breadcrumb-item"><a href="../../notebooks/ch05_counterfactuals/A05_counterfactual_replication.html"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">加州禁烟：SCM/RCM/SDID</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="https://lianxhcn.github.io/ci-policy/" class="sidebar-logo-link">
      <img src="../../images/book-logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Causal Inference</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/lianxhcn/ci-policy" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.lianxh.cn" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🏠 前言</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🍎讲义使用说明</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📌讲授计划</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../settings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🚀课前准备：环境配置</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>讲义</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/01_policy_to_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">从政策背景到研究设计</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/02_policy_to_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">政策如何进入数据</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/03_sample_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">样本选择偏误</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/04_fixed_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">固定效应：控制了什么</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/05_counterfactuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">反事实构造</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/06_did_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">双重差分：从 TWFE 到 CSDID</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/07_ddml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">双重机器学习：DDML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/08_ai_agent_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">AI Agent 辅助实证研究</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/09_reading_list.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">阅读清单</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">附录</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/appendix/A01_hci_policy_background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">韩国 HCI drive：政策背景、政策工具与亚洲四小龙</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/appendix/A01b_hci_chaebol_formation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">HCI drive 与韩国财阀的形成</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/appendix/A02_government_guidance_fund.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">政府引导基金政策梳理笔记</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/appendix/A03_heckman_selection_literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Heckman 模型扩展阅读</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/ch03_heckman/heckman_practical_notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Heckman 实操笔记</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/ch04_fixed_effects/fixed_effects_practical_notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">固定效应实操笔记</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/ch05_counterfactuals/A05_counterfactual_replication.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">加州禁烟：SCM/RCM/SDID</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/ch06_did/A06_did_method_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">DID 方法与 Stata 实操</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/ch07_ddml/A07_fwl_ddml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">双重机器学习 Stata 实操</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../exercises/exercise_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">练习概览</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#环境准备" id="toc-环境准备" class="nav-link active" data-scroll-target="#环境准备"><span class="header-section-number">G.1</span> 环境准备</a></li>
  <li><a href="#数据与-donor-pool" id="toc-数据与-donor-pool" class="nav-link" data-scroll-target="#数据与-donor-pool"><span class="header-section-number">G.2</span> 数据与 donor pool</a></li>
  <li><a href="#合成控制法scm" id="toc-合成控制法scm" class="nav-link" data-scroll-target="#合成控制法scm"><span class="header-section-number">G.3</span> 合成控制法（SCM）</a></li>
  <li><a href="#lasso-型合成控制放开约束会怎样" id="toc-lasso-型合成控制放开约束会怎样" class="nav-link" data-scroll-target="#lasso-型合成控制放开约束会怎样"><span class="header-section-number">G.4</span> Lasso 型合成控制：放开约束会怎样</a></li>
  <li><a href="#回归控制法rcm-gsc" id="toc-回归控制法rcm-gsc" class="nav-link" data-scroll-target="#回归控制法rcm-gsc"><span class="header-section-number">G.5</span> 回归控制法（RCM / GSC）</a>
  <ul class="collapse">
  <li><a href="#安慰剂检验" id="toc-安慰剂检验" class="nav-link" data-scroll-target="#安慰剂检验"><span class="header-section-number">G.5.1</span> 安慰剂检验</a></li>
  </ul></li>
  <li><a href="#合成-didsdid" id="toc-合成-didsdid" class="nav-link" data-scroll-target="#合成-didsdid"><span class="header-section-number">G.6</span> 合成 DID（SDID）</a></li>
  <li><a href="#数值汇总与口径说明" id="toc-数值汇总与口径说明" class="nav-link" data-scroll-target="#数值汇总与口径说明"><span class="header-section-number">G.7</span> 数值汇总与口径说明</a></li>
  <li><a href="#延伸与本附录的边界" id="toc-延伸与本附录的边界" class="nav-link" data-scroll-target="#延伸与本附录的边界"><span class="header-section-number">G.8</span> 延伸与本附录的边界</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../lectures/appendix/A01_hci_policy_background.html">附录</a></li><li class="breadcrumb-item"><a href="../../notebooks/ch05_counterfactuals/A05_counterfactual_replication.html"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">加州禁烟：SCM/RCM/SDID</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">附录 G — 加州禁烟：SCM/RCM/SDID</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>本附录是第五章《如果没有政策，会发生什么》的配套实操材料。第五章正文讲思路与适用条件，本附录讲怎么落地：用同一份加州禁烟数据，依次跑通合成控制法（SCM）、Lasso 型合成控制、回归控制法（RCM/GSC）与合成 DID（SDID），并解读关键输出。</p>
<p><strong>运行环境</strong>：本文件是 Jupyter Notebook 格式（<code>.ipynb</code>），可在 VS Code 中借助 <a href="https://nbstata.readthedocs.io/">nbstata</a> 内核执行 (配置方法参见 <a href="https://lianxhcn.github.io/ds2026/">数据分析与经济决策</a> 第 2-4 章)，或通过 <a href="https://aidea-labs.com/mcp-for-stata">Stata-MCP</a> 调用本地 Stata 运行。习惯直接在 Stata 中操作的读者，可使用配套的简化版 <a href="../lecture/appendix/A05_counterfactual_replication.do">A05_counterfactual_replication.do</a>（纯代码、无讲解）。</p>
<p><strong>数据</strong>：香烟消费面板 <code>smoking.dta</code> / <code>prop99_example.dta</code>，39 个州、1970–2000 年，加州（state==3）于 1989 年实施 Proposition 99。前者用于 SCM/Lasso/RCM 部分，后者（Clarke 等提供）用于 SDID 部分，两者是同一案例的不同整理版本。</p>
<p><strong>需要的外部命令</strong>：<code>synth2</code>、<code>rcm</code>、<code>sdid</code>、<code>schemepack</code>（绘图模板）。首次运行请先安装（见下一单元）。</p>
</blockquote>
<section id="环境准备" class="level2" data-number="G.1">
<h2 data-number="G.1" class="anchored" data-anchor-id="环境准备"><span class="header-section-number">G.1</span> 环境准备</h2>
<p>首次运行时安装外部命令与绘图模板；已安装可跳过。<code>nbstata</code> 环境下每个代码单元相当于一段 do 文件。</p>
<div id="ef6dfbad" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>* 安装外部命令（首次运行时取消注释执行）</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install synth2, <span class="kw">replace</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install rcm, <span class="kw">replace</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install sdid, <span class="kw">replace</span> <span class="ot">all</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install schemepack, <span class="kw">replace</span>   <span class="co">// 提供 white_tableau 等绘图模板</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="dv">scheme</span> white_tableau            <span class="co">// 全局绘图风格</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="f17d33df" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>%<span class="kw">set</span> graph_width = 6.5in </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>graph size was (8.0in, 6.0in), is now (6.5in, 6.0in).</code></pre>
</div>
</div>
<div id="c9aa93f5" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>%<span class="kw">set</span> graph_height = 4.5in </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>graph size was (6.5in, 6.0in), is now (6.5in, 4.5in).</code></pre>
</div>
</div>
</section>
<section id="数据与-donor-pool" class="level2" data-number="G.2">
<h2 data-number="G.2" class="anchored" data-anchor-id="数据与-donor-pool"><span class="header-section-number">G.2</span> 数据与 donor pool</h2>
<p>先载入数据、设定面板结构，并画出第五章开篇那张「加州 vs 其余 38 州」的原始数据图。加州是 <code>state==3</code>，是唯一的处理单位；其余 38 个州构成 donor pool（候选对照池）。</p>
<p>这张图对应正文 <strong>图 5.1</strong>。它要传达的唯一信息：加州政策后（1989 年竖线右侧）的走势看得见，但「没有政策的加州」这条线不在图上——本附录接下来所有方法，都是在补出这条看不见的线。</p>
<div id="842f26ef" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>* 数据来源（j-hai/synth-stata 镜像），课程包内也附有本地副本</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> net <span class="st">"https://github.com/j-hai/synth-stata/raw/refs/heads/main/s"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>xtset state <span class="fu">year</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="kw">des</span>                 <span class="co">// 数据概况：state, year, cigsale 及若干预测变量</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span>, sep(0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Panel variable: state (strongly balanced)
 Time variable: year, 1970 to 2000
         Delta: 1 unit

Contains data from https://github.com/j-hai/synth-stata/raw/refs/heads/main/s/s
&gt; moking.dta
 Observations:         1,209                  Tobacco Sales in 39 US States
    Variables:             7                  11 Nov 2007 23:38
-------------------------------------------------------------------------------
Variable      Storage   Display    Value
    name         type    format    label      Variable label
-------------------------------------------------------------------------------
state           long    %14.0g     state      state no
year            float   %9.0g                 year
cigsale         float   %9.0g                 cigarette sale per capita (in
                                                packs)
lnincome        float   %9.0g                 log state per capita gdp
beer            float   %9.0g                 beer consumption per capita
age15to24       float   %9.0g                 percent of state population aged
                                                15-24 years
retprice        float   %9.0g                 retail price of cigarettes
-------------------------------------------------------------------------------
Sorted by: state  year

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
       state |      1,209          20    11.25929          1         39
        year |      1,209        1985    8.947973       1970       2000
     cigsale |      1,209    118.8932     32.7674       40.7      296.2
    lnincome |      1,014    9.861634    .1706769   9.397449   10.48662
        beer |        546     23.4304     4.22319        2.5       40.4
   age15to24 |        819     .175472    .0151589   .1294482   .2036753
    retprice |      1,209    108.3419    64.38199       27.3      351.2</code></pre>
</div>
</div>
<p><strong>图 5.1 的绘制</strong>：把数据 reshape 成宽格式，加州（<code>cig3</code>）画成黑色粗线，其余 38 州画成浅色细线叠加。</p>
<div id="099030e8" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">rename</span> (cigsale age15to24 lnincome retprice) (cig age lny <span class="kw">p</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">reshape</span> <span class="kw">wide</span> cig age lny <span class="kw">p</span> beer, j(state) i(<span class="fu">year</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="fu">year</span> cig* age* lny* <span class="kw">p</span>* beer*</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">keep</span> <span class="fu">year</span> cig*</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>* 生成 38 个 donor pool 州的香烟销售均值</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>* 注意：cig3 是加州 CA，需要排除</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="kw">local</span> donor_vars</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="kw">foreach</span> i <span class="kw">of</span> numlist 1 2 4(1)39 {</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">local</span> donor_vars <span class="ot">`donor_vars'</span> cig<span class="ot">`i'</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="kw">egen</span> cig_donor_mean = <span class="fu">rowmean</span>(<span class="ot">`donor_vars'</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="kw">label</span> <span class="kw">var</span> cig_donor_mean <span class="st">"Donor pool mean"</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>#delimit ;</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="kw">twoway</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    (<span class="kw">tsline</span> cig3, lcolor(<span class="bn">black</span>) lw(<span class="bn">medthick</span>))         <span class="co">// 加州 CA</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    ,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="bn">ytitle</span>(<span class="st">"per-capita cigarette sales (in packs)"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    <span class="bn">xtitle</span>(<span class="st">"Year"</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    tline(1989, lpattern(shortdash) lcolor(<span class="bn">black</span>))</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    tlabel(1970(5)2000) <span class="kw">ylabel</span>(0(50)300);</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>#delimit <span class="kw">cr</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>* 叠加其余 38 州（donor pool）</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="kw">foreach</span> i <span class="kw">of</span> numlist 1 2 4(1)39 {</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    <span class="bn">addplot</span>: <span class="kw">tsline</span> cig<span class="ot">`i'</span>, <span class="co">///</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>        lcolor(<span class="bn">blue</span>%40) lw(thin) <span class="co">///</span></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ylabel</span>(0(50)300) </span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>* 叠加 38 个 donor pool 州的平均值</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>* 深绿色；线宽为默认值的 1.3 倍</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a><span class="bn">addplot</span>: <span class="kw">tsline</span> cig_donor_mean, <span class="co">///</span></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    lcolor(<span class="st">"green*1.3"</span>) lw(*1.3) <span class="co">///</span></span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ylabel</span>(0(50)300) <span class="co">///</span></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"California"</span> 40 <span class="st">"Donor pool mean"</span>) <span class="co">///</span></span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>           <span class="bn">ring</span>(0) pos(2) <span class="bn">cols</span>(1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)
(j = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
&gt;  29 30 31 32 33 34 35 36 37 38 39)

Data                               Long   -&gt;   Wide
-----------------------------------------------------------------------------
Number of observations            1,209   -&gt;   31          
Number of variables                   7   -&gt;   196         
j variable (39 values)            state   -&gt;   (dropped)
xij variables:
                                    cig   -&gt;   cig1 cig2 ... cig39
                                    age   -&gt;   age1 age2 ... age39
                                    lny   -&gt;   lny1 lny2 ... lny39
                                      p   -&gt;   p1 p2 ... p39
                                   beer   -&gt;   beer1 beer2 ... beer39
-----------------------------------------------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="合成控制法scm" class="level2" data-number="G.3">
<h2 data-number="G.3" class="anchored" data-anchor-id="合成控制法scm"><span class="header-section-number">G.3</span> 合成控制法（SCM）</h2>
<p>合成控制法用 donor pool 中若干州的加权组合，拼出「合成加州」。<code>synth2</code> 是对经典 <code>synth</code> 的增强版，语法直观、自带出图。</p>
<p>命令逐项解读：</p>
<ul>
<li><code>synth2 cigsale &lt;预测变量列表&gt;</code>：被解释变量是 <code>cigsale</code>，后面是用于匹配的预测变量；</li>
<li><code>cigsale(1988) cigsale(1980) cigsale(1975)</code>：把特定年份的结果变量也作为匹配目标（政策前多个时点对齐）；</li>
<li><code>trunit(3)</code>：处理单位是第 3 个州（加州）；</li>
<li><code>trperiod(1989)</code>：处理开始于 1989 年；</li>
<li><code>xperiod(1980(1)1988)</code>：预测变量的匹配窗口；</li>
<li><code>fig nested allopt</code>：出图、使用 nested 优化、尝试全部优化器（更稳但更慢）。</li>
</ul>
<div id="990a2b6d" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>xtset state <span class="fu">year</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>synth2 cigsale lnincome age15to24 retprice beer(1984(1)1988) <span class="co">///</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>       cigsale(1988) cigsale(1980) cigsale(1975),            <span class="co">///</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>       trunit(3) trperiod(1989) xperiod(1980(1)1988)         <span class="co">///</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>       fig nested allopt frame(CAdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Panel variable: state (strongly balanced)
 Time variable: year, 1970 to 2000
         Delta: 1 unit
Fitting results in the pretreatment periods:
-------------------------------------------------------------------------------
&gt; -
 Treated Unit             : California     Treatment Time           :       198
&gt; 9
-------------------------------------------------------------------------------
&gt; -
 Number of Control Units  =         38     Root Mean Squared Error  =    1.7556
&gt; 7
 Number of Covariates     =          7     R-squared                =    0.9743
&gt; 4
-------------------------------------------------------------------------------
&gt; -

Covariate balance in the pretreatment periods:
-------------------------------------------------------------------------------
&gt; -----
     Covariate     |  V.weight    Treated    Synthetic Control     Average Cont
&gt; rol  
                   |                        Value          Bias   Value        
&gt; Bias 
-------------------+-----------------------------------------------------------
&gt; -----
          lnincome |   0.0000     10.0766      9.8588    -2.16%     9.8292    -
&gt; 2.45%
         age15to24 |   0.5459      0.1735      0.1735    -0.01%     0.1725    -
&gt; 0.59%
          retprice |   0.0174     89.4222     89.4108    -0.01%    87.2661    -
&gt; 2.41%
 beer(1984(1)1988) |   0.0031     24.2800     24.2278    -0.21%    23.6553    -
&gt; 2.57%
     cigsale(1988) |   0.0049     90.1000     91.6677     1.74%   113.8237    2
&gt; 6.33%
     cigsale(1980) |   0.0066    120.2000    120.5017     0.25%   138.0895    1
&gt; 4.88%
     cigsale(1975) |   0.4221    127.1000    127.1112     0.01%   136.9316     
&gt; 7.74%
-------------------------------------------------------------------------------
&gt; -----
Note: "V.weight" is the optimal covariate weight in the diagonal of V matrix.
      "Synthetic Control" is the weighted average of donor units with optimal
      weights.
      "Average Control" is the simple average of all control units with equal
      weights.

Optimal Unit Weights:
--------------------------
     Unit    |    U.weight
-------------+------------
        Utah |     0.3340 
      Nevada |     0.2350 
     Montana |     0.2020 
    Colorado |     0.1610 
 Connecticut |     0.0680 
--------------------------
Note: The unit Alabama Arkansas Delaware Georgia Idaho Illinois Indiana Iowa
      Kansas Kentucky Louisiana Maine Minnesota Mississippi Missouri Nebraska
      NewHampshire NewMexico NorthCarolina NorthDakota Ohio Oklahoma
      Pennsylvania RhodeIsland SouthCarolina SouthDakota Tennessee Texas
      Vermont Virginia WestVirginia Wisconsin Wyoming in the donor pool get a
      weight of 0.

Prediction results in the posttreatment periods:
-----------------------------------------------------------
 Time | Actual Outcome  Synthetic Outcome  Treatment Effect
------+----------------------------------------------------
 1989 |       82.4000            89.9945           -7.5945 
 1990 |       77.8000            87.5039           -9.7039 
 1991 |       68.7000            82.1751          -13.4751 
 1992 |       67.5000            81.6075          -14.1075 
 1993 |       63.4000            81.1897          -17.7897 
 1994 |       58.6000            80.7295          -22.1295 
 1995 |       56.4000            78.5023          -22.1023 
 1996 |       54.5000            77.4827          -22.9827 
 1997 |       53.8000            77.7123          -23.9123 
 1998 |       52.3000            74.3976          -22.0976 
 1999 |       47.2000            73.5711          -26.3711 
 2000 |       41.6000            67.3550          -25.7550 
------+----------------------------------------------------
 Mean |       60.3500            79.3518          -19.0018 
-----------------------------------------------------------
Note: The average treatment effect over the posttreatment period is -19.0018.

Finished.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-7-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-7-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-7-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-7-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>输出解读 1：单位权重（Optimal Unit Weights）</strong></p>
<p><code>synth2</code> 在 38 个州里只给 5 个州分配了非零权重，其余 33 个州权重为零：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>州</th>
<th>权重</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Utah 犹他</td>
<td>0.334</td>
</tr>
<tr class="even">
<td>Nevada 内华达</td>
<td>0.235</td>
</tr>
<tr class="odd">
<td>Montana 蒙大拿</td>
<td>0.202</td>
</tr>
<tr class="even">
<td>Colorado 科罗拉多</td>
<td>0.161</td>
</tr>
<tr class="odd">
<td>Connecticut 康涅狄格</td>
<td>0.068</td>
</tr>
</tbody>
</table>
<p>这 5 个权重非负、且加总为 1（0.334+0.235+0.202+0.161+0.068 = 1.000），正是第五章强调的<strong>凸组合约束</strong>。所谓「合成加州」，就是这 5 条州曲线按此权重的加权平均——一个具体的「配方」。</p>
<p><strong>输出解读 2：预测变量平衡表</strong></p>
<p><code>synth2</code> 还会报告 R-squared（本例约 0.974）与一张平衡表，对比「真实加州」「合成加州」「所有对照州简单平均」在各预测变量上的取值。合成加州应当在多数预测变量上比简单平均更贴近真实加州——这是 SCM 相对 DID 的改进所在。</p>
<p><strong>导出三张图</strong>：<code>synth2</code> 把结果存在若干命名图形里，逐一显示并导出。</p>
<div id="0f8fb16b" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>* Table 1 的可视化（真实/合成/简单平均 三者对比）</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">display</span> bias</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"scm-rcm-Abadie10-Tab01-Fig.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>* Figure 2：真实加州 vs 合成加州（政策前拟合 + 政策后缺口）</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">display</span> pred</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"scm-Abadie2010-Fig02-pred.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>* Figure 3：处理效应 = 真实 − 合成（政策后的差距）</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">display</span> eff</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"scm-Abadie2010-Fig03-TE.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>file scm-rcm-Abadie10-Tab01-Fig.png written in PNG format
file scm-Abadie2010-Fig02-pred.png written in PNG format
file scm-Abadie2010-Fig03-TE.png written in PNG format</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-8-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-8-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>核心图：5 个非零权重州（正文图 5.2）</strong></p>
<p>这张图把 5 个非零权重州高亮出来，其余州压成灰色背景。它是理解 SCM 最直观的一张图——抽象的「凸组合权重」在这里变成「三分之一个犹他 + 四分之一个内华达 + ……」。图例里直接标出每个州的权重。</p>
<div id="083126c8" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">rename</span> (cigsale) (cig)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">keep</span> state <span class="fu">year</span> cig</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reshape</span> <span class="kw">wide</span> cig, j(state) i(<span class="fu">year</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">order</span> <span class="fu">year</span> cig*</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">keep</span> <span class="fu">year</span> cig*</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="dv">scheme</span> rainbow</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>#delimit ;</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="kw">twoway</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    (<span class="kw">tsline</span> cig3, lcolor(<span class="bn">black</span>) lw(*1.5))             <span class="co">// 加州 CA</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    ,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="bn">ytitle</span>(<span class="st">"per-capita cigarette sales (in packs)"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="bn">xtitle</span>(<span class="st">"Year"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    tline(1988, lp(shortdash) lc(<span class="bn">black</span>))</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    tlabel(1970(5)2000) tmtick(##5)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ylabel</span>(0(50)300)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    aspect(0.8) <span class="bn">ysize</span>(4) <span class="bn">xsize</span>(5.5)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"CA"</span>));</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>#delimit <span class="kw">cr</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>* 其余州压成灰色背景</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="kw">foreach</span> i <span class="kw">of</span> numlist 1 2 4(1)39 {</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    <span class="bn">addplot</span>: <span class="kw">tsline</span> cig<span class="ot">`i'</span>, lcolor(<span class="bn">black</span>*0.7%30) lw(*0.6) lp(solid) <span class="co">///</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ylabel</span>(0(50)300) tlabel(1970(5)2000) tmtick(##5)           <span class="co">///</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>        <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"CA"</span> 2 <span class="st">"rest"</span>))</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>* 高亮 5 个非零权重州</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a><span class="kw">foreach</span> i <span class="kw">of</span> numlist 34 21 19 4 5 {</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    <span class="bn">addplot</span>: <span class="kw">tsline</span> cig<span class="ot">`i'</span>, lw(*1) lp(solid)                       <span class="co">///</span></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ylabel</span>(0(50)300) tlabel(1970(5)2000) tmtick(##5)          <span class="co">///</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>        <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"CA"</span> 2 <span class="st">"rest"</span>                              <span class="co">///</span></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>                     40 <span class="st">"Utah, 0.334"</span> 41 <span class="st">"Nevada, 0.235"</span>          <span class="co">///</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>                     42 <span class="st">"Montana, 0.202"</span> 43 <span class="st">"Colorado, 0.161"</span>     <span class="co">///</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>                     44 <span class="st">"Connecticut, 0.068"</span>) <span class="ot">row</span>(2))</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"scm-Figure0-non-zero-weights.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="dv">scheme</span> white_tableau</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)
file scm-Figure0-non-zero-weights.png written in PNG format</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>SCM 小结与局限</strong></p>
<ul>
<li>反事实来源：donor pool 的凸组合；</li>
<li>识别压力：donor pool 纯净性（对照州不能受类似控烟政策污染）、预测变量选择、政策前拟合质量；</li>
<li>推断：因只有一个处理单位，依赖安慰剂/置换检验（把每个对照州轮流当假处理组，看真实加州的政策后缺口是否显著异常）；</li>
<li>约束的代价：凸组合防止了危险外推，但若真实反事实不在 donor pool 凸包内，政策前会拟合不好。</li>
</ul>
</section>
<section id="lasso-型合成控制放开约束会怎样" class="level2" data-number="G.4">
<h2 data-number="G.4" class="anchored" data-anchor-id="lasso-型合成控制放开约束会怎样"><span class="header-section-number">G.4</span> Lasso 型合成控制：放开约束会怎样</h2>
<p>第五章讲到 SCM 与 RCM 的差别是「约束 vs 灵活」。这一节用 Lasso 直接演示：把 SCM 的「非负、加总为一」约束换成 Lasso 惩罚，选出的对照州会不同，还会出现负系数和截距。</p>
<p>先把数据转成宽格式（每个州的 <code>cigsale</code> 成为一列），加州记为 <code>cig0</code>。</p>
<div id="34fd07fe" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> state = 0 <span class="kw">if</span> state == 3          <span class="co">// 把加州改记为 0，便于作被解释变量</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">rename</span> (cigsale age15to24 lnincome retprice) (cig age lny <span class="kw">p</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">reshape</span> <span class="kw">wide</span> cig age lny <span class="kw">p</span> beer, j(state) i(<span class="fu">year</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="fu">year</span> cig* age* lny* <span class="kw">p</span>* beer*</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="kw">save</span> <span class="st">"smoking_wide.dta"</span>, <span class="kw">replace</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)
(31 real changes made)
(j = 0 1 2 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
&gt;  29 30 31 32 33 34 35 36 37 38 39)

Data                               Long   -&gt;   Wide
-----------------------------------------------------------------------------
Number of observations            1,209   -&gt;   31          
Number of variables                   7   -&gt;   196         
j variable (39 values)            state   -&gt;   (dropped)
xij variables:
                                    cig   -&gt;   cig0 cig1 ... cig39
                                    age   -&gt;   age0 age1 ... age39
                                    lny   -&gt;   lny0 lny1 ... lny39
                                      p   -&gt;   p0 p1 ... p39
                                   beer   -&gt;   beer0 beer1 ... beer39
-----------------------------------------------------------------------------
(file smoking_wide.dta not found)
file smoking_wide.dta saved</code></pre>
</div>
</div>
<p><strong>Lasso 选州（plugin 选 λ）</strong></p>
<p>用政策前样本（<code>year &lt;= 1989</code>）把加州 <code>cig0</code> 对其余各州回归，Lasso 自动做变量选择。<code>select(plugin)</code> 用理论公式确定惩罚参数 λ。</p>
<div id="961f2498" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"smoking_wide.dta"</span>, <span class="kw">clear</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> TreatYear = 1989</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>lasso linear cig0 cig1-cig39 lny1-lny39 <span class="kw">if</span> <span class="fu">year</span> &lt;= <span class="ot">$TreatYear</span>, select(plugin)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>lassocoef                                <span class="co">// 查看被选中的州</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Computing plugin lambda ...
Iteration 1:     lambda = .9364963   no. of nonzero coef. =  6
Iteration 2:     lambda = .9364963   no. of nonzero coef. =  8
Iteration 3:     lambda = .9364963   no. of nonzero coef. =  7
Iteration 4:     lambda = .9364963   no. of nonzero coef. =  6
Iteration 5:     lambda = .9364963   no. of nonzero coef. =  6

Lasso linear model                          No. of obs        =         18
                                            No. of covariates =         76
Selection: Plugin heteroskedastic

--------------------------------------------------------------------------
         |                                No. of
         |                               nonzero    In-sample
      ID |     Description      lambda     coef.    R-squared          BIC
---------+----------------------------------------------------------------
     * 1 | selected lambda    .9364963         6       0.9961     65.73252
--------------------------------------------------------------------------
* lambda selected by plugin formula assuming heteroskedastic errors.

------------------------
             |  active  
-------------+----------
        cig8 |     x    
       cig15 |     x    
       cig19 |     x    
       cig21 |     x    
       cig29 |     x    
       cig34 |     x    
       _cons |     x    
------------------------
Legend:
  b - base level
  e - empty cell
  o - omitted
  x - estimated</code></pre>
</div>
</div>
<p><strong>输出对比：Lasso vs synth2 选出的州</strong></p>
<ul>
<li>Lasso（plugin）选中：cig8, cig15, cig19, cig21, cig29, cig34 + 截距</li>
<li>synth2 选中：cig4, cig5, cig19, cig21, cig34</li>
</ul>
<p>两者<strong>部分重叠</strong>（都选了 19=Montana、21=Nevada、34=Utah），但不完全相同。关键区别：Lasso 放开了非负与加总为一的约束，可以选出负系数、并带一个非零截距。同一份数据、同一个处理组，约束松一档，反事实的「配方」就换了一副面孔——这正是第五章「约束 vs 灵活」权衡的活教材。</p>
<p><strong>Lasso 反事实与 gap 图</strong></p>
<p>用惩罚系数（<code>cig0_lasso</code>）与后选择无惩罚系数（<code>cig0_post</code>，即 post-Lasso OLS）两种方式预测加州反事实，画出真实加州、两条合成线及其 gap。</p>
<div id="f6342a16" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cap dropvars cig0_lasso cig0_post gap*</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_lasso                       <span class="co">// 惩罚系数预测</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_post, postselection         <span class="co">// 后选择（无惩罚）系数预测</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_lasso = cig0 - cig0_lasso</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_post  = cig0 - cig0_post</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>#delimit ;</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="kw">tw</span> (<span class="kw">line</span> cig0       <span class="fu">year</span>, lc(<span class="bn">black</span>))</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> cig0_lasso <span class="fu">year</span>, lc(<span class="kw">red</span>))</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> cig0_post  <span class="fu">year</span>, lc(<span class="bn">blue</span>))</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> gap_lasso  <span class="fu">year</span>, lc(<span class="kw">red</span>)  lp(<span class="kw">dash</span>))</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> gap_post   <span class="fu">year</span>, lc(<span class="bn">blue</span>) lp(<span class="kw">dash</span>))</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>   ,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>   <span class="kw">ylabel</span>(-40(20)140) <span class="kw">xlabel</span>(1972(4)2000)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>   <span class="bn">xline</span>(<span class="ot">$TreatYear</span> 1988, lc(<span class="bn">gray</span>) lp(dash_dot))</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>   <span class="kw">yline</span>(0, lc(<span class="bn">black</span>) lp(<span class="bn">dot</span>))</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>   <span class="bn">xtitle</span>(<span class="st">"year"</span>) <span class="bn">ytitle</span>(<span class="st">"per-capita cigarette sales (packs)"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>   <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"CA"</span> 2 <span class="st">"syn-Lasso"</span> 3 <span class="st">"syn-Post-Lasso"</span> 4 <span class="st">"Gap"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>          <span class="bn">ring</span>(0) col(1) pos(2))</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>   aspect(0.8);</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>#delimit <span class="kw">cr</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(options xb penalized assumed; linear prediction with penalized coefficients)
(option xb assumed; linear prediction with postselection coefficients)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-12-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>进阶：λ 的选择与时间安慰剂检验（可选）</strong></p>
<p>除 <code>plugin</code> 外，还可用交叉验证（<code>cv</code>）或自适应交叉验证（<code>adaptive</code>）选 λ。把「处理年份」提前到真实政策之前（如 1984）做<strong>时间安慰剂检验</strong>：如果在假想的政策年也测出明显 gap，说明方法在制造假阳性。下面三段分别用 plugin / CV / adaptive 演示，均把 <code>TreatYear</code> 设为 1984。</p>
<div id="79d87859" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>cap <span class="kw">program</span> <span class="kw">drop</span> lasso_smoking_graph</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="kw">program</span> <span class="kw">define</span> lasso_smoking_graph</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>#d ;</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="kw">tw</span> (<span class="kw">line</span> cig0       <span class="fu">year</span>, lc(<span class="bn">black</span>)) </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> cig0_lasso <span class="fu">year</span>, lc(<span class="kw">red</span>))   </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> cig0_post  <span class="fu">year</span>, lc(<span class="bn">blue</span>))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> gap_lasso  <span class="fu">year</span>, lc(<span class="kw">red</span>)  lp(<span class="kw">dash</span>))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>   (<span class="kw">line</span> gap_post   <span class="fu">year</span>, lc(<span class="bn">blue</span>) lp(<span class="kw">dash</span>))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>   , </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">ylabel</span>(-40(20)140)   <span class="kw">xlabel</span>(1972(4)2000)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>   <span class="bn">xline</span>(<span class="ot">$TreatYear</span> 1988, lc(<span class="bn">gray</span>) lp(dash_dot)) </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>   <span class="kw">yline</span>(0, lc(<span class="bn">black</span>) lp(<span class="bn">dot</span>)) </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>   <span class="bn">xtitle</span>(<span class="st">"year"</span>) <span class="bn">ytitle</span>(<span class="st">"per-capita cigarette sales (packs)"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>   <span class="bn">legend</span>(<span class="kw">order</span>(1 <span class="st">"CA"</span> 2 <span class="st">"syn-Lasso"</span> 3 <span class="st">"syn-Post-Lasso"</span> 4 <span class="st">"Gap"</span>) <span class="bn">ring</span>(0) col(1) pos(2)) </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>   aspect(0.8) ;    <span class="co">//scheme(s1mono) </span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>#d <span class="kw">cr</span> </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code></code></pre>
</div>
</div>
<div id="66d94c70" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>* A. plugin，安慰剂年 1984</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"smoking_wide.dta"</span>, <span class="kw">clear</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> TreatYear = 1984</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>lasso linear cig0 cig1-cig39 lny1-lny39 <span class="kw">if</span> <span class="fu">year</span> &lt;= <span class="ot">$TreatYear</span>, select(plugin)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>cap dropvars cig0_lasso cig0_post gap*</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_lasso</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_post, postselect</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_lasso = cig0 - cig0_lasso</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_post  = cig0 - cig0_post</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>lasso_smoking_graph         <span class="co">// 绘图, 自编程序</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Computing plugin lambda ...
Iteration 1:     lambda = 1.101972   no. of nonzero coef. =  4
Iteration 2:     lambda = 1.101972   no. of nonzero coef. =  4

Lasso linear model                          No. of obs        =         13
                                            No. of covariates =         76
Selection: Plugin heteroskedastic

--------------------------------------------------------------------------
         |                                No. of
         |                               nonzero    In-sample
      ID |     Description      lambda     coef.    R-squared          BIC
---------+----------------------------------------------------------------
     * 1 | selected lambda    1.101972         4       0.9226     66.18965
--------------------------------------------------------------------------
* lambda selected by plugin formula assuming heteroskedastic errors.
(options xb penalized assumed; linear prediction with penalized coefficients)
(option xb assumed; linear prediction with postselection coefficients)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="ae9da0e5" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>* B. 10 折交叉验证选 λ，安慰剂年 1984</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"smoking_wide.dta"</span>, <span class="kw">clear</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> TreatYear = 1984</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>lasso linear cig0 cig1-cig39 lny1-lny39 <span class="co">///</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">if</span> <span class="fu">year</span> &lt;= <span class="ot">$TreatYear</span>, <span class="co">///</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>      select(cv, fold(10)) <span class="co">///</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>      <span class="kw">nolog</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>cap dropvars cig0_lasso cig0_post gap*</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_lasso</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_post, postselect</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_lasso = cig0 - cig0_lasso</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_post  = cig0 - cig0_post</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>lasso_smoking_graph         <span class="co">// 绘图, 自编程序</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>* 注：若 TreatYear&lt;=1983 则政策前样本太少，10 折 CV 无法执行</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Lasso linear model                          No. of obs        =         13
                                            No. of covariates =         76
Selection: Cross-validation                 No. of CV folds   =         10

--------------------------------------------------------------------------
         |                                No. of      Out-of-      CV mean
         |                               nonzero       sample   prediction
      ID |     Description      lambda     coef.    R-squared        error
---------+----------------------------------------------------------------
       1 |    first lambda    6.481684         0      -0.1541     52.97234
      84 |   lambda before    .1364332         7       0.9865     .6183389
    * 85 | selected lambda    .1302321         7       0.9866     .6170244
      86 |    lambda after    .1243129         7       0.9865     .6179679
      88 |     last lambda    .1132693         8       0.9863     .6275179
--------------------------------------------------------------------------
* lambda selected by cross-validation.
(options xb penalized assumed; linear prediction with penalized coefficients)
(option xb assumed; linear prediction with postselection coefficients)
(5 missing values generated)
(5 missing values generated)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="574a2577" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>* C. 自适应 CV 选 λ，安慰剂年 1984</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"smoking_wide.dta"</span>, <span class="kw">clear</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> TreatYear = 1984</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>lasso linear cig0 cig1-cig39 lny1-lny39 <span class="co">///</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">if</span> <span class="fu">year</span> &lt;= <span class="ot">$TreatYear</span>, <span class="co">///</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>      select(adaptive, fold(10)) <span class="co">///</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>      <span class="kw">nolog</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>cap dropvars cig0_lasso cig0_post gap*</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_lasso</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> cig0_post, postselect</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_lasso = cig0 - cig0_lasso</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> gap_post  = cig0 - cig0_post</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>lasso_smoking_graph         <span class="co">// 绘图, 自编程序</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Lasso linear model                         No. of obs         =         13
                                           No. of covariates  =         76
Selection: Adaptive                        No. of lasso steps =          2

Final adaptive step results
--------------------------------------------------------------------------
         |                                No. of      Out-of-      CV mean
         |                               nonzero       sample   prediction
      ID |     Description      lambda     coef.    R-squared        error
---------+----------------------------------------------------------------
      98 |    first lambda    1493.126         0      -0.1400     52.32459
     166 |   lambda before    2.670679         6       0.9883     .5367961
   * 167 | selected lambda    2.433423         6       0.9883     .5357959
     168 |    lambda after    2.217244         6       0.9883     .5373354
     184 |     last lambda    .5004364         7       0.9871     .5913224
--------------------------------------------------------------------------
* lambda selected by cross-validation in final adaptive step.
(options xb penalized assumed; linear prediction with penalized coefficients)
(option xb assumed; linear prediction with postselection coefficients)
(5 missing values generated)
(5 missing values generated)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-16-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>小结：</strong></p>
<ol type="1">
<li>CV 与 adaptive-CV 更偏向「预测」，但样本不能太小（政策前时期太少会失败）；</li>
<li>本例中若用 CV，Lasso 与 post-Lasso 的差异很小；</li>
<li>改变 <code>fold()</code> 的数值可观察结果变化；当 K=N 时，K 折 CV 退化为 Jackknife。</li>
</ol>
<p>Lasso 是通向 RCM 的桥：它演示了「放开凸组合约束 + 正则化选参」的思路，而 RCM 把这套思路系统化为一个可直接调用的命令。</p>
</section>
<section id="回归控制法rcm-gsc" class="level2" data-number="G.5">
<h2 data-number="G.5" class="anchored" data-anchor-id="回归控制法rcm-gsc"><span class="header-section-number">G.5</span> 回归控制法（RCM / GSC）</h2>
<p><code>rcm</code> 命令把上一节的思路封装起来：用未处理样本学习结构、预测处理组的无政策路径，可选 Lasso 做单位选择。语法极简：</p>
<div id="aa509b74" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>frame <span class="kw">reset</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"$net/smoking.dta"</span>, <span class="kw">clear</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>xtset state <span class="fu">year</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>rcm cig, trunit(3) trperiod(1989) method(lasso) criterion(cv) frame(<span class="kw">te</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>* 导出两张图</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">display</span> pred                       <span class="co">// 真实 vs 预测（反事实）</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"rcm-Abadie2010-Fig02.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">display</span> eff                        <span class="co">// 处理效应</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"rcm-Abadie2010-Fig03.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(900)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Tobacco Sales in 39 US States)

Panel variable: state (strongly balanced)
 Time variable: year, 1970 to 2000
         Delta: 1 unit

Step 1: Select the suboptimal models
(method lasso specified)

Selecting the suboptimal model...

Step 2: Select the optimal model from the suboptimal models
(criterion cv specified for leave-one-out cross-validation)

Comparing the suboptimal models containing different set of predictors:
--------------------------------------------------------------------
  K |    lambda      CVMSE     R-squared |         Operation        
----+------------------------------------+--------------------------
  1 |    10.3926    138.5578      0.0814 | add cigsale·NewHampshire 
  2 |     8.2359    100.4864      0.3957 | add cigsale·Montana 
  3 |     6.5268     69.0261      0.6068 | add cigsale·Nevada 
  4 |     3.4031     23.8443      0.8784 | add cigsale·Colorado 
  5 |     2.5743     16.4272      0.9222 | add cigsale·Illinois 
  6 |     1.6167      9.7903      0.9623 | add cigsale·Connecticut 
  7 |     0.8047      5.9113      0.9853 | add cigsale·Nebraska 
  8 |     0.4605      5.0471      0.9906 | add cigsale·Utah 
  9 |     0.3823      5.1855      0.9916 | add cigsale·Tennessee 
 10 |     0.3029      5.2701      0.9939 | add cigsale·WestVirginia 
 11 |     0.1903      4.4754      0.9968 | add cigsale·Idaho 
 10 |     0.1089      3.7906      0.9983 | drop cigsale·NewHampshire 
--------------------------------------------------------------------
Among models with 1-38 predictors, the optimal model contains 10 predictors
with CVMSE = 3.7906.

Fitting results in the pretreatment period using post-lasso OLS:
------------------------------------------------------------------------------
 Treated Unit           : Califor~a     Treatment Time            =       1989
------------------------------------------------------------------------------
 Number of Observations =        19     Root Mean Squared Error   =    0.58169
 Number of Predictors   =        10     R-squared                 =    0.99890
------------------------------------------------------------------------------
------------------------------------------------------------------------------
cigsale·Ca~a | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
cigsale·Co~o |     0.0401     0.0591     0.68   0.516      -0.0961      0.1763
cigsale·Co~t |     0.1555     0.0823     1.89   0.096      -0.0343      0.3453
cigsale·Id~o |     0.0977     0.0770     1.27   0.240      -0.0798      0.2752
cigsale·Il~s |     0.1636     0.0830     1.97   0.084      -0.0278      0.3551
cigsale·Mo~a |     0.0790     0.0941     0.84   0.426      -0.1381      0.2961
cigsale·N~ka |     0.2223     0.1121     1.98   0.083      -0.0362      0.4808
cigsale·N~da |     0.1449     0.0234     6.20   0.000       0.0910      0.1988
cigsale·Te~e |    -0.3288     0.0506    -6.50   0.000      -0.4455     -0.2121
cigsale·Utah |     0.2553     0.1065     2.40   0.043       0.0098      0.5008
cigsale·We~a |     0.1059     0.0499     2.12   0.067      -0.0093      0.2211
       _cons |    12.1112    10.1978     1.19   0.269     -11.4050     35.6275
------------------------------------------------------------------------------

Prediction results in the posttreatment period using post-lasso OLS:
-----------------------------------------------------------
 Time | Actual Outcome  Predicted Outcome  Treatment Effect
------+----------------------------------------------------
 1989 |       82.4000            88.3050           -5.9050 
 1990 |       77.8000            85.2309           -7.4309 
 1991 |       68.7000            81.7155          -13.0155 
 1992 |       67.5000            80.0131          -12.5131 
 1993 |       63.4000            81.0122          -17.6122 
 1994 |       58.6000            78.2354          -19.6354 
 1995 |       56.4000            74.9933          -18.5933 
 1996 |       54.5000            74.7744          -20.2744 
 1997 |       53.8000            74.9967          -21.1967 
 1998 |       52.3000            71.8880          -19.5880 
 1999 |       47.2000            71.8063          -24.6063 
 2000 |       41.6000            66.9323          -25.3324 
------+----------------------------------------------------
 Mean |       60.3500            77.4919          -17.1419 
-----------------------------------------------------------
Note: The average treatment effect over the posttreatment period is -17.1419.

Finished.
file rcm-Abadie2010-Fig02.png written in PNG format
file rcm-Abadie2010-Fig03.png written in PNG format</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-17-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-17-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>输出解读：post-lasso OLS 的系数</strong></p>
<p><code>rcm</code> 报告政策前用 post-lasso OLS 拟合的系数（本例 R² ≈ 0.98）：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>预测州</th>
<th>系数</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Colorado</td>
<td>0.063</td>
</tr>
<tr class="even">
<td>Montana</td>
<td>0.418</td>
</tr>
<tr class="odd">
<td>Nevada</td>
<td>0.218</td>
</tr>
<tr class="even">
<td>New Hampshire</td>
<td>0.038</td>
</tr>
<tr class="odd">
<td>截距 <code>_cons</code></td>
<td>12.46</td>
</tr>
</tbody>
</table>
<p>对照 F.3 的 SCM 权重（都非负、加总为 1），这里的系数<strong>没有非负约束、不加总为 1、还带一个 12.46 的截距</strong>。这就是「约束 vs 灵活」在数值上的直接体现：RCM 换取了更强的拟合，代价是系数不再有「配方份额」那样干净的解释。</p>
<p><strong>处理效应</strong>：政策后各年的处理效应从 1989 年的约 −8 逐步扩大到 2000 年的约 −33，政策后期平均约 <strong>−23.1</strong>（packs per capita）。注意这个数字与 SCM、SDID 的口径不同（见 F.7 对比），不能直接比较哪个「更准」。</p>
<section id="安慰剂检验" class="level3" data-number="G.5.1">
<h3 data-number="G.5.1" class="anchored" data-anchor-id="安慰剂检验"><span class="header-section-number">G.5.1</span> 安慰剂检验</h3>
<p>包括两类：</p>
<ul>
<li>截面安慰剂检验：把每个对照州轮流当假处理组，计算其 gap，画出真实加州的 gap 是否显著异常；</li>
<li>时间安慰剂检验：把处理年份提前到真实政策之前（如 1985），看是否也测出明显 gap。</li>
</ul>
<p>上述两个检验可以通过 <code>placebo()</code> 选项一次性完成。</p>
<div id="3c107e88" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">//Implement placebo tests using all fake treatment units in the donor pool, and fake treatment time 1985</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>rcm cig, trunit(3) trperiod(1989) method(lasso) criterion(cv) <span class="co">///</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>         placebo(unit period(1984))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Step 1: Select the suboptimal models
(method lasso specified)

Selecting the suboptimal model...

Step 2: Select the optimal model from the suboptimal models
(criterion cv specified for leave-one-out cross-validation)

Comparing the suboptimal models containing different set of predictors:
--------------------------------------------------------------------
  K |    lambda      CVMSE     R-squared |         Operation        
----+------------------------------------+--------------------------
  1 |    10.3926    138.5578      0.0814 | add cigsale·NewHampshire 
  2 |     8.2359    100.4864      0.3957 | add cigsale·Montana 
  3 |     6.5268     69.0261      0.6068 | add cigsale·Nevada 
  4 |     3.4031     23.8443      0.8784 | add cigsale·Colorado 
  5 |     2.5743     16.4272      0.9222 | add cigsale·Illinois 
  6 |     1.6167      9.7903      0.9623 | add cigsale·Connecticut 
  7 |     0.8047      5.9113      0.9853 | add cigsale·Nebraska 
  8 |     0.4605      5.0471      0.9906 | add cigsale·Utah 
  9 |     0.3823      5.1855      0.9916 | add cigsale·Tennessee 
 10 |     0.3029      5.2701      0.9939 | add cigsale·WestVirginia 
 11 |     0.1903      4.4754      0.9968 | add cigsale·Idaho 
 10 |     0.1089      3.7906      0.9983 | drop cigsale·NewHampshire 
--------------------------------------------------------------------
Among models with 1-38 predictors, the optimal model contains 10 predictors
with CVMSE = 3.7906.

Fitting results in the pretreatment period using post-lasso OLS:
------------------------------------------------------------------------------
 Treated Unit           : Califor~a     Treatment Time            =       1989
------------------------------------------------------------------------------
 Number of Observations =        19     Root Mean Squared Error   =    0.58169
 Number of Predictors   =        10     R-squared                 =    0.99890
------------------------------------------------------------------------------
------------------------------------------------------------------------------
cigsale·Ca~a | Coefficient  Std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
cigsale·Co~o |     0.0401     0.0591     0.68   0.516      -0.0961      0.1763
cigsale·Co~t |     0.1555     0.0823     1.89   0.096      -0.0343      0.3453
cigsale·Id~o |     0.0977     0.0770     1.27   0.240      -0.0798      0.2752
cigsale·Il~s |     0.1636     0.0830     1.97   0.084      -0.0278      0.3551
cigsale·Mo~a |     0.0790     0.0941     0.84   0.426      -0.1381      0.2961
cigsale·N~ka |     0.2223     0.1121     1.98   0.083      -0.0362      0.4808
cigsale·N~da |     0.1449     0.0234     6.20   0.000       0.0910      0.1988
cigsale·Te~e |    -0.3288     0.0506    -6.50   0.000      -0.4455     -0.2121
cigsale·Utah |     0.2553     0.1065     2.40   0.043       0.0098      0.5008
cigsale·We~a |     0.1059     0.0499     2.12   0.067      -0.0093      0.2211
       _cons |    12.1112    10.1978     1.19   0.269     -11.4050     35.6275
------------------------------------------------------------------------------

Prediction results in the posttreatment period using post-lasso OLS:
-----------------------------------------------------------
 Time | Actual Outcome  Predicted Outcome  Treatment Effect
------+----------------------------------------------------
 1989 |       82.4000            88.3050           -5.9050 
 1990 |       77.8000            85.2309           -7.4309 
 1991 |       68.7000            81.7155          -13.0155 
 1992 |       67.5000            80.0131          -12.5131 
 1993 |       63.4000            81.0122          -17.6122 
 1994 |       58.6000            78.2354          -19.6354 
 1995 |       56.4000            74.9933          -18.5933 
 1996 |       54.5000            74.7744          -20.2744 
 1997 |       53.8000            74.9967          -21.1967 
 1998 |       52.3000            71.8880          -19.5880 
 1999 |       47.2000            71.8063          -24.6063 
 2000 |       41.6000            66.9323          -25.3324 
------+----------------------------------------------------
 Mean |       60.3500            77.4919          -17.1419 
-----------------------------------------------------------
Note: The average treatment effect over the posttreatment period is -17.1419.

Implementing in-space placebo test using fake treatment unit Alabama...Arkansas
&gt; ...Colorado...Connecticut...Delaware...Georgia...Idaho...Illinois...Indiana..
&gt; .Iowa...Kansas...Kentucky...Louisiana...Maine...Minnesota...Mississippi...Mis
&gt; souri...Montana...Nebraska...Nevada...NewHampshire...NewMexico...NorthCarolin
&gt; a...NorthDakota...Ohio...Oklahoma...Pennsylvania...RhodeIsland...SouthCarolin
&gt; a...SouthDakota...Tennessee...Texas...Utah...Vermont...Virginia...WestVirgini
&gt; a...Wisconsin...Wyoming...

In-space placebo test results using fake treatment units:
-------------------------------------------------------------------------------
      Unit     |  Pre MSPE  Post MSPE   Post/Pre MSPE    Pre MSPE of Fake Unit/
               |                                       Pre MSPE of Treated Unit
---------------+---------------------------------------------------------------
    California |    0.3384   329.0633       972.5173                    1.0000 
       Alabama |    0.9072    54.9255        60.5424                    2.6812 
      Arkansas |    1.1922    19.6078        16.4466                    3.5235 
      Colorado |    4.1426    24.0732         5.8111                   12.2431 
   Connecticut |    1.0216   504.8030       494.1413                    3.0192 
      Delaware |    1.9630   103.4568        52.7029                    5.8015 
       Georgia |    1.1261   258.8375       229.8481                    3.3282 
         Idaho |    6.6522    43.5348         6.5444                   19.6600 
      Illinois |    3.0723    23.0302         7.4960                    9.0800 
       Indiana |   12.3106     7.2096         0.5856                   36.3830 
          Iowa |    8.7781  1046.8045       119.2514                   25.9430 
        Kansas |    9.1591    11.4804         1.2534                   27.0689 
      Kentucky |    7.2148  3390.5614       469.9473                   21.3226 
     Louisiana |    0.5579   175.4502       314.4600                    1.6489 
         Maine |    6.8918   205.9667        29.8857                   20.3682 
     Minnesota |   12.0828   218.2688        18.0645                   35.7095 
   Mississippi |    0.7528    54.0167        71.7543                    2.2248 
      Missouri |    0.2493    87.6291       351.4534                    0.7369 
       Montana |    2.3828   426.6798       179.0652                    7.0422 
      Nebraska |    0.3644    15.4478        42.3955                    1.0769 
        Nevada |   20.3267   426.0337        20.9594                   60.0736 
  NewHampshire |   28.2646   681.3402        24.1058                   83.5335 
     NewMexico |    2.1847    22.6750        10.3788                    6.4568 
 NorthCarolina |   14.9268   264.9914        17.7528                   44.1147 
   NorthDakota |    2.9056    39.4738        13.5852                    8.5874 
          Ohio |    0.4054    38.8056        95.7282                    1.1980 
      Oklahoma |    1.5424   464.4083       301.1029                    4.5583 
  Pennsylvania |    1.5488     5.5210         3.5646                    4.5775 
   RhodeIsland |    7.8156  3762.3328       481.3853                   23.0984 
 SouthCarolina |    0.3955   164.4681       415.8650                    1.1688 
   SouthDakota |    2.5512    32.6110        12.7826                    7.5399 
     Tennessee |    2.1977    23.5144        10.6993                    6.4952 
         Texas |    0.8704   200.4718       230.3311                    2.5723 
          Utah |    2.1962    21.5140         9.7961                    6.4906 
       Vermont |    6.6915   112.5418        16.8186                   19.7762 
      Virginia |    1.0531   326.7857       310.3149                    3.1123 
  WestVirginia |    2.9818   684.1183       229.4281                    8.8126 
     Wisconsin |    2.7930    50.2112        17.9775                    8.2545 
       Wyoming |   15.6433  1660.3462       106.1378                   46.2324 
-------------------------------------------------------------------------------
Note: The probability of obtaining a post/pretreatment MSPE ratio as large as
      California's is 0.0256.

In-space placebo test results using fake treatment units (continued):
----------------------------------------------------------------
 Time |  Treatment Effect      p-value of Treatment Effect      
      |                     Two-sided   Right-sided   Left-sided
------+---------------------------------------------------------
 1989 |          -5.9050       0.1795       0.9231       0.1026 
 1990 |          -7.4309       0.4103       0.8462       0.1795 
 1991 |         -13.0155       0.2564       0.8974       0.1282 
 1992 |         -12.5131       0.2821       0.8974       0.1282 
 1993 |         -17.6122       0.2308       0.8974       0.1282 
 1994 |         -19.6354       0.2821       0.8974       0.1282 
 1995 |         -18.5933       0.3333       0.8462       0.1795 
 1996 |         -20.2744       0.2821       0.8974       0.1282 
 1997 |         -21.1967       0.2564       0.9231       0.1026 
 1998 |         -19.5880       0.3590       0.8718       0.1538 
 1999 |         -24.6063       0.2564       0.9487       0.0769 
 2000 |         -25.3324       0.2821       0.9487       0.0769 
----------------------------------------------------------------
Note: (1) The two-sided p-value of the treatment effect for a particular
      period is defined as the frequency that the absolute values of the
      placebo effects are greater than or equal to the absolute value of
      treatment effect.
      (2) The right-sided (left-sided) p-value of the treatment effect for a
      particular period is defined as the frequency that the placebo effects
      are greater (smaller) than or equal to the treatment effect.
      (3) If the estimated treatment effect is positive, then the right-sided
      p-value is recommended; whereas the left-sided p-value is recommended
      if the estimated treatment effect is negative.

Implementing in-time placebo test using fake treatment time 1984...

In-time placebo test results using fake treatment time 1984:
-----------------------------------------------------------
 Time | Actual Outcome  Predicted Outcome  Treatment Effect
------+----------------------------------------------------
 1984 |      104.8000           103.0105            1.7895 
 1985 |      102.8000           105.5193           -2.7193 
 1986 |       99.7000           104.2389           -4.5389 
 1987 |       97.5000           105.1217           -7.6217 
 1988 |       90.1000           102.2364          -12.1364 
 1989 |       82.4000            98.5779          -16.1779 
 1990 |       77.8000            95.8314          -18.0314 
 1991 |       68.7000            87.3190          -18.6190 
 1992 |       67.5000            84.9525          -17.4525 
 1993 |       63.4000            85.5245          -22.1245 
 1994 |       58.6000            82.9465          -24.3465 
 1995 |       56.4000            84.7783          -28.3783 
 1996 |       54.5000            82.9162          -28.4162 
 1997 |       53.8000            82.0870          -28.2870 
 1998 |       52.3000            83.7798          -31.4798 
 1999 |       47.2000            83.0519          -35.8519 
 2000 |       41.6000            78.2107          -36.6107 
------+----------------------------------------------------
 Mean |       71.7118            91.1825          -19.4707 
-----------------------------------------------------------
Note: The average treatment effect over the posttreatment period is -19.4707.

Finished.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-18-output-10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>小结：</strong></p>
<p>从上述结果来看，RCM 的反事实构造与 SCM 相比，拟合更好、gap 更小，但系数解释不再直观。安慰剂检验显示，真实加州的 gap 在对照组中显著异常，支持政策效应的存在。</p>
<p>然而，时间安慰剂检验显示，若把处理年份提前到 1984 年，仍然测出明显 gap，说明 RCM 在政策前时期的拟合可能存在过度拟合的风险。可以考虑在政策前时期增加更多预测变量，或使用更严格的正则化方法（如 adaptive-CV）来缓解过拟合。</p>
</section>
</section>
<section id="合成-didsdid" class="level2" data-number="G.6">
<h2 data-number="G.6" class="anchored" data-anchor-id="合成-didsdid"><span class="header-section-number">G.6</span> 合成 DID（SDID）</h2>
<p>SDID 同时给单位和时间加权。<code>sdid</code> 命令（Clarke 等）语法为 <code>sdid Y S T D</code>，其中 D 是二元处理变量。SDID 部分使用 Clarke 提供的 <code>prop99_example.dta</code>（与前面同案例、不同整理版本，处理变量已命名为 <code>treated</code>）。</p>
<div id="ea9774a9" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> <span class="kw">set</span> www.damianclarke.net/stata/</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="kw">webuse</span> prop99_example.dta, <span class="kw">clear</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="kw">encode</span> state, <span class="kw">gen</span>(id_state)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>xtset id_state <span class="fu">year</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="kw">xtdes</span>                                    <span class="co">// 确认为强平衡面板：39 州 × 31 年</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(prefix now "http://www.damianclarke.net/stata")

Panel variable: id_state (strongly balanced)
 Time variable: year, 1970 to 2000
         Delta: 1 unit

id_state:  1, 2, ..., 39                                     n =         39
    year:  1970, 1971, ..., 2000                             T =         31
           Delta(year) = 1 unit
           Span(year)  = 31 periods
           (id_state*year uniquely identifies each observation)

Distribution of T_i:   min      5%     25%       50%       75%     95%     max
                        31      31      31        31        31      31      31

     Freq.  Percent    Cum. |  Pattern
 ---------------------------+---------------------------------
       39    100.00  100.00 |  1111111111111111111111111111111
 ---------------------------+---------------------------------
       39    100.00         |  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</code></pre>
</div>
</div>
<p><strong>基础用法</strong>：<code>vce(placebo)</code> 用安慰剂法做推断（适合单一处理组的情形），<code>seed()</code> 固定随机种子以复现。</p>
<div id="ff3ddee3" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>sdid packspercapita state <span class="fu">year</span> treated, <span class="kw">vce</span>(placebo) <span class="dv">seed</span>(1213)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Placebo replications (50). This may take some time.
----+--- 1 ---+--- 2 ---+--- 3 ---+--- 4 ---+--- 5
..................................................     50


Synthetic Difference-in-Differences Estimator

-----------------------------------------------------------------------------
packsperca~a |     ATT     Std. Err.     t      P&gt;|t|    [95% Conf. Interval]
-------------+---------------------------------------------------------------
     treated | -15.60383    9.87941    -1.58    0.114   -34.96712     3.75946
-----------------------------------------------------------------------------
95% CIs and p-values are based on large-sample approximations.
Refer to Arkhangelsky et al., (2021) for theoretical derivations.</code></pre>
</div>
</div>
<p><strong>输出解读</strong>：ATT ≈ <strong>−15.60</strong>（packs per capita），安慰剂标准误约 9–10，p 值约 0.08–0.11（因随机抽样，换 seed 或 reps 会略有变化）。这是 SDID 对全体政策后时期加权平均的 ATT。</p>
<p><strong>带图输出</strong>：<code>graph</code> 选项出两张图——趋势图（真实 vs 合成加州）与权重图（单位权重 + 时间权重）。<code>graph_export(stub, .png)</code> 会自动生成 <code>stub_trendsYYYY.png</code> 和 <code>stub_weightsYYYY.png</code>（YYYY 为处理年份 1989）。这是正文 <strong>图 5.4</strong> 的来源。</p>
<div id="f99395a8" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>#delimit ;</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sdid packspercapita state <span class="fu">year</span> treated,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>     <span class="kw">vce</span>(placebo) <span class="dv">seed</span>(1213) reps(100)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>     <span class="kw">graph</span> g1on</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>     g2_opt(<span class="kw">ylabel</span>(0(25)150) <span class="bn">ytitle</span>(<span class="st">"Packs per capita"</span>) <span class="dv">scheme</span>(white_tableau))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>     g1_opt(<span class="bn">xtitle</span>(<span class="st">""</span>) <span class="kw">ylabel</span>(-35(5)10) <span class="dv">scheme</span>(white_tableau))</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>     graph_export(SDID_cig_002, .png);</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>#delimit <span class="kw">cr</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Placebo replications (100). This may take some time.
----+--- 1 ---+--- 2 ---+--- 3 ---+--- 4 ---+--- 5
..................................................     50
..................................................     100


Synthetic Difference-in-Differences Estimator

-----------------------------------------------------------------------------
packsperca~a |     ATT     Std. Err.     t      P&gt;|t|    [95% Conf. Interval]
-------------+---------------------------------------------------------------
     treated | -15.60383    9.68177    -1.61    0.107   -34.57975     3.37209
-----------------------------------------------------------------------------
95% CIs and p-values are based on large-sample approximations.
Refer to Arkhangelsky et al., (2021) for theoretical derivations.
(file SDID_cig_002weights1989.png not found)
file SDID_cig_002weights1989.png written in PNG format
(file SDID_cig_002trends1989.png not found)
file SDID_cig_002trends1989.png written in PNG format</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-21-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>三种方法同框对比（正文数值对比的来源）</strong></p>
<p><code>sdid</code> 的 <code>method()</code> 选项可一键切换 SDID / DID / SC，用同一份数据、同一套绘图参数跑三遍，最能看清三者差异。<code>vce(noinference)</code> 跳过推断、只出点估计与图，加快速度。</p>
<div id="4d84fe43" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> <span class="kw">yx</span> <span class="st">"packspercapita state year treated"</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="kw">global</span> <span class="dv">scheme</span> <span class="st">"scheme(white_tableau)"</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>* SDID</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>sdid <span class="ot">$yx</span>, method(sdid) <span class="kw">vce</span>(noinference) <span class="kw">graph</span>                     <span class="co">///</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>     g1_opt(<span class="kw">ylabel</span>(-110(20)50) <span class="bn">xtitle</span>(<span class="st">""</span>) <span class="ot">$scheme</span>) g1on           <span class="co">///</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>     g2_opt(<span class="kw">ylabel</span>(0(25)150) <span class="bn">ytitle</span>(<span class="st">"Packs per capita"</span>) <span class="ot">$scheme</span>)  <span class="co">///</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>     graph_export(comp_cig_01_sdid, .png)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>* DID</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>sdid <span class="ot">$yx</span>, method(did) <span class="kw">vce</span>(noinference) <span class="kw">graph</span> msize(small)         <span class="co">///</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>     g1_opt(<span class="kw">ylabel</span>(-110(20)50) <span class="bn">xtitle</span>(<span class="st">""</span>) <span class="ot">$scheme</span>) g1on           <span class="co">///</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>     g2_opt(<span class="kw">ylabel</span>(0(25)150) <span class="bn">ytitle</span>(<span class="st">"Packs per capita"</span>) <span class="ot">$scheme</span>)  <span class="co">///</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>     graph_export(comp_cig_02_did, .png)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>* SC</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>sdid <span class="ot">$yx</span>, method(<span class="kw">sc</span>) <span class="kw">vce</span>(noinference) <span class="kw">graph</span> msize(small)          <span class="co">///</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>     g1_opt(<span class="kw">ylabel</span>(-110(20)50) <span class="bn">xtitle</span>(<span class="st">""</span>) <span class="ot">$scheme</span>) g1on           <span class="co">///</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>     g2_opt(<span class="kw">ylabel</span>(0(25)150) <span class="bn">ytitle</span>(<span class="st">"Packs per capita"</span>) <span class="ot">$scheme</span>)  <span class="co">///</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>     graph_export(comp_cig_03_sc, .png)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Synthetic Difference-in-Differences Estimator

-----------------------------------------------------------------------------
packsperca~a |     ATT     Std. Err.     t      P&gt;|t|    [95% Conf. Interval]
-------------+---------------------------------------------------------------
     treated | -15.60383          .        .        .           .           .
-----------------------------------------------------------------------------
95% CIs and p-values are based on large-sample approximations.
Refer to Arkhangelsky et al., (2021) for theoretical derivations.
(file comp_cig_01_sdidweights1989.png not found)
file comp_cig_01_sdidweights1989.png written in PNG format
(file comp_cig_01_sdidtrends1989.png not found)
file comp_cig_01_sdidtrends1989.png written in PNG format


Difference-in-Differences Estimator

-----------------------------------------------------------------------------
packsperca~a |     ATT     Std. Err.     t      P&gt;|t|    [95% Conf. Interval]
-------------+---------------------------------------------------------------
     treated | -27.34911          .        .        .           .           .
-----------------------------------------------------------------------------
95% CIs and p-values are based on large-sample approximations.

(file comp_cig_02_didweights1989.png not found)
file comp_cig_02_didweights1989.png written in PNG format
(file comp_cig_02_didtrends1989.png not found)
file comp_cig_02_didtrends1989.png written in PNG format


Synthetic Control

-----------------------------------------------------------------------------
packsperca~a |     ATT     Std. Err.     t      P&gt;|t|    [95% Conf. Interval]
-------------+---------------------------------------------------------------
     treated | -19.61966          .        .        .           .           .
-----------------------------------------------------------------------------
95% CIs and p-values are based on large-sample approximations.

(file comp_cig_03_scweights1989.png not found)
file comp_cig_03_scweights1989.png written in PNG format
(file comp_cig_03_sctrends1989.png not found)
file comp_cig_03_sctrends1989.png written in PNG format</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-22-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="A05_counterfactual_replication_files/figure-html/cell-22-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="数值汇总与口径说明" class="level2" data-number="G.7">
<h2 data-number="G.7" class="anchored" data-anchor-id="数值汇总与口径说明"><span class="header-section-number">G.7</span> 数值汇总与口径说明</h2>
<p>三种方法在加州数据上给出的 ATT（均为 packs per capita）：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>方法</th>
<th>命令</th>
<th>ATT</th>
<th>口径</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DID</td>
<td><code>sdid, method(did)</code></td>
<td><strong>−27.3</strong></td>
<td>双向 FE、等权平均，政策后全期</td>
</tr>
<tr class="even">
<td>SC</td>
<td><code>sdid, method(sc)</code></td>
<td><strong>−19.6</strong></td>
<td>单位加权，政策后全期</td>
</tr>
<tr class="odd">
<td>SDID</td>
<td><code>sdid, method(sdid)</code></td>
<td><strong>−15.6</strong></td>
<td>单位+时间加权，政策后全期</td>
</tr>
<tr class="even">
<td>RCM</td>
<td><code>rcm, method(lasso)</code></td>
<td><strong>−23.1</strong></td>
<td>post-lasso 预测，政策后期简单平均</td>
</tr>
</tbody>
</table>
<p><strong>为什么数值不同？</strong> 这不是「谁算错了」，而是反事实构造方式不同的直接后果：</p>
<ul>
<li>DID 用等权平均，最受「加州与对照州长期趋势不平行」的拖累，绝对值最大；</li>
<li>SC 用截面加权贴近加州，缓解了不平行；</li>
<li>SDID 再叠加时间加权，把更多权重放在与政策期更相关的年份，进一步收窄；</li>
<li>RCM 的 −23.1 与前三者口径不同（政策后期简单平均、且样本/命令实现不同），<strong>不能与 SDID 的 −15.6 直接比大小</strong>。</li>
</ul>
<p><strong>教学要点</strong>：第五章正文只作定性结论（不同方法给出不同数值，因反事实构造方式不同）。若在论文里报告，务必标注每个数字的口径（加权方式、时间范围、推断方法），避免读者误以为某个数「最准」。真正稳健的做法是像 Lane (2025) 那样报告多种方法、看结论方向是否一致，而非纠结单一点估计。</p>
</section>
<section id="延伸与本附录的边界" class="level2" data-number="G.8">
<h2 data-number="G.8" class="anchored" data-anchor-id="延伸与本附录的边界"><span class="header-section-number">G.8</span> 延伸与本附录的边界</h2>
<p>本附录只做「怎么用」。以下内容留给正文、第七章或专门文献：</p>
<ul>
<li><strong>SDID 的推导</strong>（个体权重与时间权重的优化问题、bootstrap/jackknife 方差、DID/SC/SDID 三估计量的统一形式）见第五章 SDID 幻灯片与 Arkhangelsky et al.&nbsp;(2021)、Clarke et al.&nbsp;(2023)；</li>
<li><strong>RDD 的实操</strong>（带宽、局部多项式、密度操纵检验、稳健偏差校正）本案例数据不适用，见第七章扩展阅读中的 Calonico–Cattaneo–Titiunik 系列；</li>
<li><strong>交错处理下的 DID 方法选择</strong>（Goodman-Bacon 分解、csdid、Sun–Abraham、BJS 等）是第六章的主题；</li>
<li><strong>机器学习预测反事实/nuisance function</strong>（DDML）是第七章的主题，与 F.4–F.5 的「放开约束 + 正则化」思路一脉相承。</li>
</ul>
<p><strong>参考文献</strong></p>
<ul>
<li>Abadie, A., Diamond, A., &amp; Hainmueller, J. (2010). Synthetic control methods for comparative case studies: Estimating the effect of California’s tobacco control program. <em>Journal of the American Statistical Association</em>, 105(490), 493–505. <a href="https://doi.org/10.1198/jasa.2009.ap08746">Link</a>, <a href="https://economics.mit.edu/sites/default/files/publications/Synthetic%20Control%20Methods.pdf">PDF</a>, <a href="https://scholar.google.com/scholar?q=Synthetic+control+methods+for+comparative+case+studies+Estimating+the+effect+of+California%27s+tobacco+control+program">Google</a>.</li>
<li>Arkhangelsky, D., Athey, S., Hirshberg, D. A., Imbens, G. W., &amp; Wager, S. (2021). Synthetic difference-in-differences. <em>American Economic Review</em>, 111(12), 4088–4118. <a href="https://doi.org/10.1257/aer.20190159">Link</a>, <a href="https://www.nber.org/system/files/working_papers/w25532/w25532.pdf">PDF</a>, <a href="https://scholar.google.com/scholar?q=Synthetic+difference-in-differences+Arkhangelsky+Athey+Hirshberg+Imbens+Wager">Google</a>.</li>
<li>Angrist, J. D., &amp; Lavy, V. (1999). Using Maimonides’ rule to estimate the effect of class size on scholastic achievement. <em>The Quarterly Journal of Economics</em>, 114(2), 533–575. <a href="https://doi.org/10.1162/003355399556061">Link</a>, <a href="https://piketty.pse.ens.fr/files/AngristLavy1999.pdf">PDF</a>, <a href="https://scholar.google.com/scholar?q=Using+Maimonides+rule+to+estimate+the+effect+of+class+size+on+scholastic+achievement">Google</a>.</li>
<li>Ciccia, D. (2024). A short note on event-study synthetic difference-in-differences estimators. <em>arXiv:2407.09565</em>. <a href="https://doi.org/10.48550/arXiv.2407.09565">Link</a>, <a href="https://arxiv.org/pdf/2407.09565.pdf">PDF</a>, <a href="https://scholar.google.com/scholar?q=A+short+note+on+event-study+synthetic+difference-in-differences+estimators">Google</a>.</li>
<li>Clarke, D., Pailañir, D., Athey, S., &amp; Imbens, G. (2024). On synthetic difference-in-differences and related estimation methods in Stata. <em>The Stata Journal</em>, 24(4), 557–598. <a href="https://doi.org/10.1177/1536867X241297914">Link</a>, <a href="https://journals.sagepub.com/doi/pdf/10.1177/1536867X241297914">PDF</a>, <a href="https://scholar.google.com/scholar?q=On+synthetic+difference-in-differences+and+related+estimation+methods+in+Stata">Google</a>. <a href="https://github.com/Daniel-Pailanir/sdid">github</a></li>
<li>Lee, D. S. (2008). Randomized experiments from non-random selection in U.S. House elections. <em>Journal of Econometrics</em>, 142(2), 675–697. <a href="https://doi.org/10.1016/j.jeconom.2007.05.004">Link</a>, <a href="https://www.princeton.edu/~davidlee/wp/RDrand.pdf">PDF</a>, <a href="https://scholar.google.com/scholar?q=Randomized+experiments+from+non-random+selection+in+U.S.+House+elections">Google</a>.</li>
<li>Yan, G., &amp; Chen, Q. (2022). rcm: A command for the regression control method. <em>The Stata Journal</em>, 22(4), 842–883. <a href="https://doi.org/10.1177/1536867X221140960">Link</a>, <a href="https://journals.sagepub.com/doi/pdf/10.1177/1536867X221140960">PDF</a>, <a href="https://scholar.google.com/scholar?q=rcm+A+command+for+the+regression+control+method">Google</a>.</li>
<li>Yan, G., &amp; Chen, Q. (2023). synth2: Synthetic control method with placebo tests, robustness test, and visualization. <em>The Stata Journal</em>, 23(3), 597–624. <a href="https://doi.org/10.1177/1536867X231195278">Link</a>, <a href="https://journals.sagepub.com/doi/pdf/10.1177/1536867X231195278">PDF</a>, <a href="https://scholar.google.com/scholar?q=synth2+Synthetic+control+method+with+placebo+tests+robustness+test+and+visualization">Google</a>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/lianxhcn\.github\.io\/ci-policy\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../notebooks/ch04_fixed_effects/fixed_effects_practical_notes.html" class="pagination-link" aria-label="固定效应实操笔记">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">固定效应实操笔记</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../notebooks/ch06_did/A06_did_method_selection.html" class="pagination-link" aria-label="DID 方法与 Stata 实操">
        <span class="nav-page-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">DID 方法与 Stata 实操</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="https://www.lianxh.cn">lianxh.cn</a></p>
</div>
    <div class="nav-footer-right">
<p>基于 <a href="https://quarto.org/">Quarto</a> 构建</p>
</div>
  </div>
</footer>




</body></html>